### PR TITLE
Switch JLLPrefixes over to using Git.jl

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
On Windows, if you are an admin, you could do `git config --system core.longpaths true` (instead of `git config --global core.longpaths true`).

Then it will apply to all users.

**Comment by DilumAluthge** [comment]
@staticfloat Actually, what we should do is, when we build the Windows Dockerfiles, we should run `git config --system core.longpaths true` as part of the Dockerfile.

And we should also run it as part of the recipe for building the Windows VM base images.

**Comment by staticfloat** [comment]
Yes, that's what I've done, and I'm confused as to why it's not working here.  :(

You can see in the debugging, those values are set properly: https://buildkite.com/julialang/jllprefixes-dot-jl/builds/54#018651cd-cb10-43d8-995e-018b13c7db23/264-275

**Comment by staticfloat** [comment]
Oh wow, this is..... this is so bad: https://github.com/libgit2/libgit2/blob/80742e159c3221fd853d9a0fe735b382a7e3419d/docs/win32-longpaths.md?plain=1#L28-L33

**Comment by DilumAluthge** [comment]
What does command-line Git do?

**Comment by staticfloat** [comment]
It works, of course. :)

**Pull request merged**
